[package]
name = "crusty-maimai"
version = "0.5.1"
edition = "2021"
authors = ["swyrin", "foxeiz"]

[dependencies]
reqwest = { version = "0.11.24", features = ["blocking", "cookies"] }
scraper = "0.18.1"

[dev-dependencies]
dotenv = "0.15.0"
